# Generated by Django 3.0.4 on 2020-07-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag1'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag2'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag3'),
        ),
    ]
