# Generated by Django 3.0.4 on 2020-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200707_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tag1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tag2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tag3'),
        ),
    ]
